### PR TITLE
Mention that the Johansson guides use ipython

### PR DESCRIPTION
**Pull request by sargas**
This is important since we are directly linking people past the
introduction, and various automagic (and magic) jupyter commands are
used.

### CODE REVIEW

**Comment by terencezl** [comment]
Not only mentioning ipython, but also the mentioning of notebook is needed.

**Comment by sargas** [comment]
Why? Is there any magic commands that only work in the notebook?

**Comment by sargas** [comment]
Okay, I'll concede

**Comment by terencezl** [comment]
Because the lectures are ipython notebooks after all. If we are giving line by line instructions, they have to use `ipython notebook`.

**Pull request merged**
